language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '6'

env:
  global:
    - SLS_DEBUG=true

before_script:
  - npm prune

script:
  - yarn eslint

after_success:
  - yarn semantic-release
